# Generated by Django 3.2.3 on 2021-06-23 17:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_days', models.IntegerField()),
                ('num_reps', models.IntegerField()),
                ('oil_reference', models.CharField(choices=[('BRENT', 'BRENT'), ('WTI', 'WTI')], max_length=50)),
                ('sim_model', models.CharField(choices=[('MBG', 'Movimiento Browniano Geometrico simple'), ('MBGMR', 'Movimiento Browniano Gometrico simple con Reversion a la Media')], max_length=50)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('petition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petition.petition')),
            ],
        ),
    ]
