# Generated by Django 3.2.3 on 2021-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
