# Generated by Django 3.2.3 on 2021-07-06 19:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_petition_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petition.petition')),
            ],
        ),
    ]
