# Generated by Django 3.2.3 on 2021-07-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_alter_confidenceinterval_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidenceinterval',
            name='petition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petition.petition'),
        ),
    ]
