# Generated by Django 3.2.3 on 2021-07-06 22:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_alter_confidenceinterval_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ci',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None), default=None, size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConfidenceInterval',
        ),
    ]
